package vista;

import conexion.Conexion;
import conexion.DAO_Producto;
import conexion.DAO_RegistrarCompra;
import controlador.Ctrl_compra;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.CabeceraCompra;
import modelo.DetalleCompra;
import modelo.Producto;
import modelo.Proveedor;

/**
 *
 * @author ediso
 */
public class InterCompra extends javax.swing.JInternalFrame {


    public InterCompra() {
        initComponents();
        this.setSize(new Dimension(1000, 604));
        this.setTitle("Gestionar Compras");
        //Cargar tabla
       

        //insertar imagen en nuestro JLabel
        ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(1000, 604, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //metodo para inicializar la tabla de los productos
  

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_compras = new javax.swing.JTable();
        jButton_añadir = new javax.swing.JButton();
        txt_proveedor_buscar = new javax.swing.JTextField();
        jComboBox_proveedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        txt_cantidad1 = new javax.swing.JTextField();
        txt_precio1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_descripcion1 = new javax.swing.JTextField();
        jComboBox_iva1 = new javax.swing.JComboBox<>();
        jComboBox_categoria1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton_busca_proveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total_pagar = new javax.swing.JTextField();
        jComboBox_tipoPago = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_estadoPago = new javax.swing.JComboBox<>();
        jButton_RegistrarCompra = new javax.swing.JButton();
        lblTotalDolar = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Compras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_comprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_compras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 630, 210));

        jButton_añadir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_añadir.setText("Añadir");
        jButton_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 30));

        txt_proveedor_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_proveedor_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, -1));

        jComboBox_proveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Proveedor:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Proveedor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        txt_nombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        txt_cantidad1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        txt_precio1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Cantidad:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Precio:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Descripcion:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        txt_descripcion1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 170, -1));

        jComboBox_iva1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_iva1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione iva:", "No grava iva", "12%", "14%" }));
        getContentPane().add(jComboBox_iva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jComboBox_categoria1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_categoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_categoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("IVA:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Categorias:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, -1));

        jButton_busca_proveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_proveedor.setText("Buscar");
        jButton_busca_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_proveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_busca_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Subtotal:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Descuento:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Iva:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Total a pagar:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Tipo de pago:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txt_subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_subtotal.setEnabled(false);
        jPanel2.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, -1));

        txt_descuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descuento.setEnabled(false);
        jPanel2.add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        txt_iva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_iva.setEnabled(false);
        jPanel2.add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        txt_total_pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_pagar.setEnabled(false);
        jPanel2.add(txt_total_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        jComboBox_tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de pago", "Tarjeta", "Efectivo", "Pago Movil", "Transferencia" }));
        jPanel2.add(jComboBox_tipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Estado:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jComboBox_estadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estado del pago", "Pagado", "Pendiente" }));
        jPanel2.add(jComboBox_estadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 320, 220));

        jButton_RegistrarCompra.setBackground(new java.awt.Color(51, 255, 255));
        jButton_RegistrarCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_RegistrarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N
        jButton_RegistrarCompra.setText("Registrar Compra");
        jButton_RegistrarCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_RegistrarCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_RegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 170, 100));

        lblTotalDolar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalDolar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTotalDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 170, 40));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirActionPerformed
  
    }//GEN-LAST:event_jButton_añadirActionPerformed

    private void jButton_busca_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_proveedorActionPerformed
   
    }//GEN-LAST:event_jButton_busca_proveedorActionPerformed

    private void jButton_RegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarCompraActionPerformed

    }//GEN-LAST:event_jButton_RegistrarCompraActionPerformed
    int idArrayList = 0;
    private void jTable_comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_comprasMouseClicked
      /*  int fila_point = jTable_compras.rowAtPoint(evt.getPoint());
        int columna_point = 0;
        if (fila_point > -1) {
//            idArrayList = (int) modeloDatosProductos.getValueAt(fila_point, columna_point);
        }
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estas seguro de que quieres eliminar " + Ctrl_compra.cantidad
                + " unidad(es) de " + Ctrl_compra.nombre + " del Carrito?", "Confirmar Eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) { //presione si
            Ctrl_compra.listaDetalle.remove(idArrayList - 1);
            Ctrl_compra.listaTablaProductos();
           // this.calcularTotales();
        }*/
    }//GEN-LAST:event_jTable_comprasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_RegistrarCompra;
    public javax.swing.JButton jButton_añadir;
    public javax.swing.JButton jButton_busca_proveedor;
    public javax.swing.JComboBox<String> jComboBox_categoria1;
    public javax.swing.JComboBox<String> jComboBox_estadoPago;
    public javax.swing.JComboBox<String> jComboBox_iva1;
    public javax.swing.JComboBox<String> jComboBox_proveedor;
    public javax.swing.JComboBox<String> jComboBox_tipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_compras;
    private javax.swing.JLabel lblTotalDolar;
    public javax.swing.JTextField txt_cantidad1;
    public javax.swing.JTextField txt_descripcion1;
    public javax.swing.JTextField txt_descuento;
    public javax.swing.JTextField txt_iva;
    public javax.swing.JTextField txt_nombre1;
    public javax.swing.JTextField txt_precio1;
    public javax.swing.JTextField txt_proveedor_buscar;
    public javax.swing.JTextField txt_subtotal;
    public javax.swing.JTextField txt_total_pagar;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_RegistrarCompra() {
        return jButton_RegistrarCompra;
    }

    public void setjButton_RegistrarCompra(JButton jButton_RegistrarCompra) {
        this.jButton_RegistrarCompra = jButton_RegistrarCompra;
    }

    public JButton getjButton_añadir() {
        return jButton_añadir;
    }

    public void setjButton_añadir(JButton jButton_añadir) {
        this.jButton_añadir = jButton_añadir;
    }

    public JButton getjButton_busca_proveedor() {
        return jButton_busca_proveedor;
    }

    public void setjButton_busca_proveedor(JButton jButton_busca_proveedor) {
        this.jButton_busca_proveedor = jButton_busca_proveedor;
    }

    public JComboBox<String> getjComboBox_tipoPago() {
        return jComboBox_tipoPago;
    }

    public void setjComboBox_tipoPago(JComboBox<String> jComboBox_tipoPago) {
        this.jComboBox_tipoPago = jComboBox_tipoPago;
    }

  

    public JComboBox<String> getjComboBox_categoria1() {
        return jComboBox_categoria1;
    }

    public void setjComboBox_categoria1(JComboBox<String> jComboBox_categoria1) {
        this.jComboBox_categoria1 = jComboBox_categoria1;
    }

    public JComboBox<String> getjComboBox_iva1() {
        return jComboBox_iva1;
    }

    public void setjComboBox_iva1(JComboBox<String> jComboBox_iva1) {
        this.jComboBox_iva1 = jComboBox_iva1;
    }

    public JComboBox<String> getjComboBox_proveedor() {
        return jComboBox_proveedor;
    }

    public void setjComboBox_proveedor(JComboBox<String> jComboBox_proveedor) {
        this.jComboBox_proveedor = jComboBox_proveedor;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public static JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static void setjScrollPane1(JScrollPane jScrollPane1) {
        InterCompra.jScrollPane1 = jScrollPane1;
    }

    public static JTable getjTable_compras() {
        return jTable_compras;
    }

    public static void setjTable_compras(JTable jTable_compras) {
        InterCompra.jTable_compras = jTable_compras;
    }

    public JTextField getTxt_cantidad1() {
        return txt_cantidad1;
    }

    public void setTxt_cantidad1(JTextField txt_cantidad1) {
        this.txt_cantidad1 = txt_cantidad1;
    }

    public JTextField getTxt_descripcion1() {
        return txt_descripcion1;
    }

    public void setTxt_descripcion1(JTextField txt_descripcion1) {
        this.txt_descripcion1 = txt_descripcion1;
    }

    public JTextField getTxt_descuento() {
        return txt_descuento;
    }

    public void setTxt_descuento(JTextField txt_descuento) {
        this.txt_descuento = txt_descuento;
    }

    public JTextField getTxt_iva() {
        return txt_iva;
    }

    public void setTxt_iva(JTextField txt_iva) {
        this.txt_iva = txt_iva;
    }

    public JTextField getTxt_nombre1() {
        return txt_nombre1;
    }

    public void setTxt_nombre1(JTextField txt_nombre1) {
        this.txt_nombre1 = txt_nombre1;
    }

    public JTextField getTxt_precio1() {
        return txt_precio1;
    }

    public void setTxt_precio1(JTextField txt_precio1) {
        this.txt_precio1 = txt_precio1;
    }

    public JTextField getTxt_proveedor_buscar() {
        return txt_proveedor_buscar;
    }

    public void setTxt_proveedor_buscar(JTextField txt_proveedor_buscar) {
        this.txt_proveedor_buscar = txt_proveedor_buscar;
    }

    public JTextField getTxt_subtotal() {
        return txt_subtotal;
    }

    public void setTxt_subtotal(JTextField txt_subtotal) {
        this.txt_subtotal = txt_subtotal;
    }

    public JTextField getTxt_total_pagar() {
        return txt_total_pagar;
    }

    public void setTxt_total_pagar(JTextField txt_total_pagar) {
        this.txt_total_pagar = txt_total_pagar;
    }

    public JLabel getLblTotalDolar() {
        return lblTotalDolar;
    }

    public void setLblTotalDolar(JLabel lblTotalDolar) {
        this.lblTotalDolar = lblTotalDolar;
    }

    public JComboBox<String> getjComboBox_estadoPago() {
        return jComboBox_estadoPago;
    }

    public void setjComboBox_estadoPago(JComboBox<String> jComboBox_estadoPago) {
        this.jComboBox_estadoPago = jComboBox_estadoPago;
    }

    
 
}
