package vista;

import conexion.Conexion;
import conexion.DAO_RegistrarCompra;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.CabeceraCompra;

/**
 *
 * @author ediso
 */
public class InterGestionarCompras extends javax.swing.JInternalFrame {

 public int idCompra;

    public InterGestionarCompras() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Compras");

        this.CargarTablaCompras();
        //insertar imagen en nuestro JLabel
        ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_compras = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_total_pagar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jComboBox_proveedor = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_tipoPago = new javax.swing.JComboBox<>();
        jComboBox_estadoPago = new javax.swing.JComboBox<>();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Compras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_compras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 130, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Total Pagar:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        txt_total_pagar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_total_pagar.setEnabled(false);
        jPanel3.add(txt_total_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Proveedor:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Estado:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        txt_fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fecha.setEnabled(false);
        jPanel3.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        jComboBox_proveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione proveedor:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_proveedorActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 170, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Tipo de pago:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jComboBox_tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de pago:", "Tarjeta", "Efectivo", "Pago Movil", "Transferencia" }));
        jPanel3.add(jComboBox_tipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        jComboBox_estadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagado", "Pendiente" }));
        jComboBox_estadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_estadoPagoActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_estadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 120));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jComboBox_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_proveedorActionPerformed

    private void jComboBox_estadoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_estadoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_estadoPagoActionPerformed

  /*
     * *****************************************************
     * metodo para mostrar todos los clientes registrados
     * *****************************************************
     */
    private void CargarTablaCompras() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select cc.idCabeceraCompra as id, concat(p.nombre, ' ', p.apellido) as proveedor, "
                + "cc.valorPagar as total,cc.formaPago as forma_pago, cc.fechaCompra as fecha, cc.estado "
                + "from tb_cabecera_compra as cc, tb_proveedor as p where cc.idProveedor = p.idProveedor;";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarCompras.jTable_compras = new JTable(model);
            InterGestionarCompras.jScrollPane1.setViewportView(InterGestionarCompras.jTable_compras);

            model.addColumn("N°");//ID
            model.addColumn("Proveedor");
            model.addColumn("Total Pagar");
            model.addColumn("Forma de Pago");
            model.addColumn("Fecha Compra");
            model.addColumn("estado");

            while (rs.next()) {
                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    if (i == 6) {
                        String estado = String.valueOf(rs.getObject(i + 1));

                    } else {
                        fila[i] = rs.getObject(i + 1);
                    }
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla de compras: " + e);
        }
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_compras.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_compras.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCompra = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosVentaSeleccionada(idCompra);//metodo
                }
            }
        });
    }


    /*
     * **************************************************
     * Metodo que envia datos seleccionados
     * **************************************************
     */
    private void EnviarDatosVentaSeleccionada(int idCompra) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select cc.idCabeceraCompra, cc.idProveedor, concat(p.nombre, ' ', p.apellido) as proveedor, "
                    + "cc.valorPagar,cc.formaPago, cc.fechaCompra, cc.estado  from tb_cabecera_compra as cc, "
                    + "tb_proveedor as p where  cc.idCabeceraCompra = '" + idCompra + "' and cc.idProveedor = p.idProveedor;");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                jComboBox_proveedor.setSelectedItem(rs.getString("proveedor"));
                jComboBox_tipoPago.setSelectedItem(rs.getString("formaPago"));
                jComboBox_estadoPago.setSelectedItem(rs.getString("estado"));
                txt_total_pagar.setText(rs.getString("valorPagar"));
                txt_fecha.setText(rs.getString("fechaCompra"));

            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar Compra: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_actualizar;
    public javax.swing.JComboBox<String> jComboBox_estadoPago;
    public javax.swing.JComboBox<String> jComboBox_proveedor;
    public javax.swing.JComboBox<String> jComboBox_tipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_compras;
    public javax.swing.JTextField txt_fecha;
    public javax.swing.JTextField txt_total_pagar;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_actualizar() {
        return jButton_actualizar;
    }

    public void setjButton_actualizar(JButton jButton_actualizar) {
        this.jButton_actualizar = jButton_actualizar;
    }

    public JComboBox<String> getjComboBox_estadoPago() {
        return jComboBox_estadoPago;
    }

    public void setjComboBox_estadoPago(JComboBox<String> jComboBox_estadoPago) {
        this.jComboBox_estadoPago = jComboBox_estadoPago;
    }

    public JComboBox<String> getjComboBox_tipoPago() {
        return jComboBox_tipoPago;
    }

    public void setjComboBox_tipoPago(JComboBox<String> jComboBox_tipoPago) {
        this.jComboBox_tipoPago = jComboBox_tipoPago;
    }


    public JComboBox<String> getjComboBox_proveedor() {
        return jComboBox_proveedor;
    }

    public void setjComboBox_proveedor(JComboBox<String> jComboBox_proveedor) {
        this.jComboBox_proveedor = jComboBox_proveedor;
    }

    public static JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static void setjScrollPane1(JScrollPane jScrollPane1) {
        InterGestionarCompras.jScrollPane1 = jScrollPane1;
    }

    public static JTable getjTable_compras() {
        return jTable_compras;
    }

    public static void setjTable_compras(JTable jTable_compras) {
        InterGestionarCompras.jTable_compras = jTable_compras;
    }

    public JTextField getTxt_fecha() {
        return txt_fecha;
    }

    public void setTxt_fecha(JTextField txt_fecha) {
        this.txt_fecha = txt_fecha;
    }

    public JTextField getTxt_total_pagar() {
        return txt_total_pagar;
    }

    public void setTxt_total_pagar(JTextField txt_total_pagar) {
        this.txt_total_pagar = txt_total_pagar;
    }

    

}
