/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Marialyh
 */
public class InterCierreCaja1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterCierreCaja
     */
    public InterCierreCaja1() {
        initComponents();
        this.setSize(new Dimension(1000, 600));
        this.setTitle("Cuentas por Cobrar");
        
         ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(1000, 600, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JTextField();
        txtTotalVentas = new javax.swing.JTextField();
        txtTotalBs = new javax.swing.JTextField();
        txtTotalDolares = new javax.swing.JTextField();
        txtTotalTransferencia = new javax.swing.JTextField();
        txtTotalPagoMovil = new javax.swing.JTextField();
        txtTotalEfectivo = new javax.swing.JTextField();
        txtTotalTarjeta = new javax.swing.JTextField();
        txtTotalGeneral = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_Calcular = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jButton_registrarCierre = new javax.swing.JButton();
        jButton_verHistorial = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Tarjeta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Efectivo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_PagoMovil = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Transferencia = new javax.swing.JTable();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cierre de Caja");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Total Tarjeta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Total Transferencia:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Total Pago Movil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Total Efectivo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Total Dolares:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total Otros(Bs):");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Total General:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtFechaActual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFechaActual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFechaActual.setText("24/04/2024");
        jPanel1.add(txtFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 190, 20));

        txtTotalVentas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalVentas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalVentas.setText("0.00 Bs");
        jPanel1.add(txtTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 190, 20));

        txtTotalBs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalBs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalBs.setText("0.00");
        jPanel1.add(txtTotalBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 190, 20));

        txtTotalDolares.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalDolares.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalDolares.setText("0.00");
        jPanel1.add(txtTotalDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, 20));

        txtTotalTransferencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalTransferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalTransferencia.setText("0.00");
        jPanel1.add(txtTotalTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 190, 20));

        txtTotalPagoMovil.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalPagoMovil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPagoMovil.setText("0.00");
        jPanel1.add(txtTotalPagoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 20));

        txtTotalEfectivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalEfectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalEfectivo.setText("0.00");
        jPanel1.add(txtTotalEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, 20));

        txtTotalTarjeta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalTarjeta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalTarjeta.setText("0.00");
        jPanel1.add(txtTotalTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 190, 20));

        txtTotalGeneral.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotalGeneral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalGeneral.setText("0.00 Bs");
        jPanel1.add(txtTotalGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Total Ventas del Día:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 930, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Calcular.setText("Calcular");
        jPanel4.add(jButton_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 40));

        jButton_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_limpiar.setText("Limpiar");
        jPanel4.add(jButton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        jButton_registrarCierre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_registrarCierre.setText("Registrar Cierre");
        jPanel4.add(jButton_registrarCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        jButton_verHistorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_verHistorial.setText("Ver Historial");
        jPanel4.add(jButton_verHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 180, 280));

        jTable_Tarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Tarjeta);

        jTabbedPane3.addTab("Tarjeta", jScrollPane1);

        jTable_Efectivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Efectivo);

        jTabbedPane3.addTab("Efectivo", jScrollPane2);

        jTable_PagoMovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable_PagoMovil);

        jTabbedPane3.addTab("Pago movil", jScrollPane3);

        jTable_Transferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable_Transferencia);

        jTabbedPane3.addTab("Transferencia", jScrollPane4);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 720, 290));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButton_Calcular() {
        return jButton_Calcular;
    }

    public void setjButton_Calcular(JButton jButton_Calcular) {
        this.jButton_Calcular = jButton_Calcular;
    }

    public JButton getjButton_limpiar() {
        return jButton_limpiar;
    }

    public void setjButton_limpiar(JButton jButton_limpiar) {
        this.jButton_limpiar = jButton_limpiar;
    }

    public JButton getjButton_registrarCierre() {
        return jButton_registrarCierre;
    }

    public void setjButton_registrarCierre(JButton jButton_registrarCierre) {
        this.jButton_registrarCierre = jButton_registrarCierre;
    }

    public JButton getjButton_verHistorial() {
        return jButton_verHistorial;
    }

    public void setjButton_verHistorial(JButton jButton_verHistorial) {
        this.jButton_verHistorial = jButton_verHistorial;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JTabbedPane getjTabbedPane3() {
        return jTabbedPane3;
    }

    public void setjTabbedPane3(JTabbedPane jTabbedPane3) {
        this.jTabbedPane3 = jTabbedPane3;
    }

    public JTable getjTable_Efectivo() {
        return jTable_Efectivo;
    }

    public void setjTable_Efectivo(JTable jTable_Efectivo) {
        this.jTable_Efectivo = jTable_Efectivo;
    }

    public JTable getjTable_PagoMovil() {
        return jTable_PagoMovil;
    }

    public void setjTable_PagoMovil(JTable jTable_PagoMovil) {
        this.jTable_PagoMovil = jTable_PagoMovil;
    }

    public JTable getjTable_Tarjeta() {
        return jTable_Tarjeta;
    }

    public void setjTable_Tarjeta(JTable jTable_Tarjeta) {
        this.jTable_Tarjeta = jTable_Tarjeta;
    }

    public JTable getjTable_Transferencia() {
        return jTable_Transferencia;
    }

    public void setjTable_Transferencia(JTable jTable_Transferencia) {
        this.jTable_Transferencia = jTable_Transferencia;
    }

  
    public JTextField getTxtFechaActual() {
        return txtFechaActual;
    }

    public void setTxtFechaActual(JTextField txtFechaActual) {
        this.txtFechaActual = txtFechaActual;
    }

    public JTextField getTxtTotalBs() {
        return txtTotalBs;
    }

    public void setTxtTotalBs(JTextField txtTotalBs) {
        this.txtTotalBs = txtTotalBs;
    }

    public JTextField getTxtTotalDolares() {
        return txtTotalDolares;
    }

    public void setTxtTotalDolares(JTextField txtTotalDolares) {
        this.txtTotalDolares = txtTotalDolares;
    }

    public JTextField getTxtTotalEfectivo() {
        return txtTotalEfectivo;
    }

    public void setTxtTotalEfectivo(JTextField txtTotalEfectivo) {
        this.txtTotalEfectivo = txtTotalEfectivo;
    }

    public JTextField getTxtTotalGeneral() {
        return txtTotalGeneral;
    }

    public void setTxtTotalGeneral(JTextField txtTotalGeneral) {
        this.txtTotalGeneral = txtTotalGeneral;
    }

    public JTextField getTxtTotalPagoMovil() {
        return txtTotalPagoMovil;
    }

    public void setTxtTotalPagoMovil(JTextField txtTotalPagoMovil) {
        this.txtTotalPagoMovil = txtTotalPagoMovil;
    }

    public JTextField getTxtTotalTarjeta() {
        return txtTotalTarjeta;
    }

    public void setTxtTotalTarjeta(JTextField txtTotalTarjeta) {
        this.txtTotalTarjeta = txtTotalTarjeta;
    }

    public JTextField getTxtTotalTransferencia() {
        return txtTotalTransferencia;
    }

    public void setTxtTotalTransferencia(JTextField txtTotalTransferencia) {
        this.txtTotalTransferencia = txtTotalTransferencia;
    }

    public JTextField getTxtTotalVentas() {
        return txtTotalVentas;
    }

    public void setTxtTotalVentas(JTextField txtTotalVentas) {
        this.txtTotalVentas = txtTotalVentas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Calcular;
    public javax.swing.JButton jButton_limpiar;
    public javax.swing.JButton jButton_registrarCierre;
    public javax.swing.JButton jButton_verHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTable jTable_Efectivo;
    public javax.swing.JTable jTable_PagoMovil;
    public javax.swing.JTable jTable_Tarjeta;
    public javax.swing.JTable jTable_Transferencia;
    public javax.swing.JTextField txtFechaActual;
    public javax.swing.JTextField txtTotalBs;
    public javax.swing.JTextField txtTotalDolares;
    public javax.swing.JTextField txtTotalEfectivo;
    public javax.swing.JTextField txtTotalGeneral;
    public javax.swing.JTextField txtTotalPagoMovil;
    public javax.swing.JTextField txtTotalTarjeta;
    public javax.swing.JTextField txtTotalTransferencia;
    public javax.swing.JTextField txtTotalVentas;
    // End of variables declaration//GEN-END:variables
}
